version: '3.7'

services:

  web:
    build:
      context: .
      cache_from:
        - sanqitang/docker-ci-cache:latest
    image: sanqitang/docker-ci-cache:latest
    ports:
      - 5001:5000
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/users
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/users_test
    depends_on:
      - db

  db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
